[package]
name = "deployer"
version = "0.1.0"
authors = ["Jonathan Lange <jml@mumak.net>"]

[dependencies]
clap = "~2.19.0"
iron = "0.4.*"
prometheus = "0.2.8"
router = "0.4.*"
simplelog = "^0.4.2"

[dependencies.logger]
git = "https://github.com/iron/logger.git"
